@startuml

|#CCFFCC|


start

repeat
    :get power status;
    switch (""SHUTDOWN_TRIGGER in"")
'    if (SHUTDOWN_TRIGGER in "AC Power", "All") then (yes)
    case (""["AC Power", "All"]"")
        if (""AC_STATUS == "GOOD""") then (yes)
            if (""AC_LOSS_TIME > 0"") then (yes)
                :=AC Power restored,
                ==shutdown cancelled
                ....
                <code>
                AC_LOSS_TIME = 0
                </code>;
            endif
        else
            if (""AC_LOSS_TIME == 0"")) then (yes)
                :=AC Power lost
                ....
                <code>
                AC_LOSS_TIME = time.time()
                soundBuzzer(times=1)
                </code>;
            endif
            if (""time.time() >= AC_LOSS_TIME+WAIT_SECONDS"") then (yes)
                #tomato:=Shutdown in progress
                ....
                <code>
                soundBuzzer(times=1)
                **safeShutdown**
                </code>;
            endif
        endif
'    elseif (SHUTDOWN_TRIGGER in "SoC", "All") then (yes)
    case (""["Soc", "All"]"")
        if (""SOC <= SOC_THRESHOLD"") then (yes)
            #tomato:=Shutdown in progress
            ....
            <code>
            soundBuzzer(times=2)
            **safeShutdown**
            </code>;
        endif
'    elseif (SHUTDOWN_TRIGGER in "Voltage", "All") then (yes)
    case (""["Voltage", "All"]"")
        if (""VOLTAGE <= VOLTAGE_THRESHOLD"") then (yes)
            #tomato:=Shutdown in progress
            ....
            <code>
            soundBuzzer(times=3)
            **safeShutdown**
            </code>;
        endif
'    endif
    endswitch
    :""time.sleep(10)"";
repeat while;


@enduml
